### ISSUE TITLE
Cannot read property 'lifecycleVisualizerStore' of undefined

### ISSUE THREAD

**Issue by hally9k** [Oblosys/react-lifecycle-visualizer#1]
I couldn't get this working. When I wrap a component in the `traceLifecycle` HOC I just get the above error because `_this.context` is undefined.

**Comment by Oblosys** [comment]
Does the component you're tracing have an explicit constructor? And if so, could you try to add the `context` parameter to it?

    constructor(props, context) {
      super(props, context);
      ..
    }

**Comment by Oblosys** [comment]
Nice, thanks for the info. I'll reopen this issue, as I may have a solution that works even when not specifying `context`, but it's quite a big change and needs some more testing.
